Repository vectara/vectara-docs, pull requests merged in 2025-01, with the labels that each got.

#352 docs(update): Add new HHEM supported languages and some content enhancements
  www/docs/learn/hallucination-evaluation.md
Labels: New Features, Documentation and Feature Enhancements

#379 docs(update): Update HHEM documentation for HHME-2.2
  www/docs/learn/hallucination-evaluation.md
Labels: New Features

#381 docs(update): Add HHEM 2.2 enhancements to Release Notes
  www/docs/release-notes.mdx
Labels: Documentation and Feature Enhancements

#378 feat(new): Add documentation for the new Knee Reranking feature
  www/docs/api-reference/search-apis/reranking.md
  www/docs/api-reference/search-apis/search.md
  www/docs/learn/knee-reranking.md
  www/docs/release-notes.mdx
  www/sidebars.js
Labels: New Features

#383 docs(ia): Add a dedicated changelog for documentation updates, API enhancements and bug fixes
  www/docs/DocCHANGELOG.md
  www/docs/welcome.mdx
  www/docusaurus.config.js
  www/sidebars.js
Labels: Documentation and Feature Enhancements, Information Architecture Changes

#384 docs(fix): Fix OAuth2 URL and update screenshot
  www/docs/learn/authentication/oauth.md
  www/static/img/api_playground_listcorpora.png
Labels: Documentation Fixes

#385 docs(platform): Add documentation changelog workflow
  .github/workflows/generate-doc-changelog.yml
Labels: Documentation Fixes

#386 doc(platform): Update Doc Changelog workflow action
  .github/workflows/generate-doc-changelog.yml
Labels: Platform Updates

#388 doc(fix): Fix encoder example with correct value
  www/docs/rest-api/create-api-key.api.mdx
  www/docs/rest-api/create-app-client.api.mdx
  www/docs/rest-api/create-chat-turn.api.mdx
  www/docs/rest-api/create-chat.api.mdx
  www/docs/rest-api/create-corpus-document.api.mdx
  www/docs/rest-api/create-corpus.api.mdx
  www/docs/rest-api/create-user.api.mdx
  www/docs/rest-api/delete-api-key.api.mdx
  www/docs/rest-api/delete-app-client.api.mdx
  www/docs/rest-api/delete-chat-turn.api.mdx
  www/docs/rest-api/delete-chat.api.mdx
  www/docs/rest-api/delete-corpus-document.api.mdx
  www/docs/rest-api/delete-corpus.api.mdx
  www/docs/rest-api/delete-user.api.mdx
  www/docs/rest-api/get-api-key.api.mdx
  www/docs/rest-api/get-app-client.api.mdx
  www/docs/rest-api/get-chat-turn.api.mdx
  www/docs/rest-api/get-chat.api.mdx
  www/docs/rest-api/get-corpus-document.api.mdx
  www/docs/rest-api/get-corpus.api.mdx
  www/docs/rest-api/get-job.api.mdx
  www/docs/rest-api/get-query-histories.api.mdx
  www/docs/rest-api/get-query-history.api.mdx
  www/docs/rest-api/get-user.api.mdx
  www/docs/rest-api/list-api-keys.api.mdx
  www/docs/rest-api/list-app-client.api.mdx
  www/docs/rest-api/list-chat-turns.api.mdx
  www/docs/rest-api/list-chats.api.mdx
  www/docs/rest-api/list-corpora.api.mdx
  www/docs/rest-api/list-corpus-documents.api.mdx
  www/docs/rest-api/list-encoders.api.mdx
  www/docs/rest-api/list-generation-presets.api.mdx
  www/docs/rest-api/list-jobs.api.mdx
  www/docs/rest-api/list-ll-ms.api.mdx
  www/docs/rest-api/list-rerankers.api.mdx
  www/docs/rest-api/list-users.api.mdx
  www/docs/rest-api/query-corpus.api.mdx
  www/docs/rest-api/query.api.mdx
  www/docs/rest-api/replace-corpus-document-metadata.api.mdx
  www/docs/rest-api/replace-filter-attributes.api.mdx
  www/docs/rest-api/reset-corpus.api.mdx
  www/docs/rest-api/reset-user-password.api.mdx
  www/docs/rest-api/search-corpus.api.mdx
  www/docs/rest-api/update-api-key.api.mdx
  www/docs/rest-api/update-app-client.api.mdx
  www/docs/rest-api/update-chat-turn.api.mdx
  www/docs/rest-api/update-corpus-document.api.mdx
  www/docs/rest-api/update-corpus.api.mdx
  www/docs/rest-api/update-user.api.mdx
  www/docs/rest-api/upload-file.api.mdx
  www/static/vectara-oas-v2.yaml
Labels: Documentation Fixes, Example Updates

#391 docs(fix): Fix broken links in generative prompts
  www/docs/generative-prompts.mdx
  www/docusaurus.config.js
Labels: Documentation Fixes

#394 deprecate: Uploading JSON in API v2
  www/docs/api-reference/indexing-apis/file-upload/file_formats.md
  www/docs/api-reference/indexing-apis/file-upload/file_upload.md
  www/docs/api-reference/indexing-apis/file-upload/supported_file_formats.md
  www/docs/api-reference/search-apis/interpreting-responses/highlighting.md
  www/docs/learn/data-ingestion.md
  www/docs/learn/document-structuring.md
  www/docs/migration-guide-api-v2.md
  www/sidebars.js
Labels: Deprecated, API Changes, Documentation Fixes

#396 docs(ia): Improve Getting Started section layout
  www/docs/api-reference/search-apis/search.md
  www/docs/getting-started.mdx
  www/docs/release-notes.mdx
  www/sidebars.js
Labels: Documentation and Feature Enhancements, Information Architecture Changes
