Repository vectara/vectara-docs, pull requests merged in 2025-03, with the labels that each got.

#414 feat(new): Add content for new integration between Vectara and Confluent
  www/docs/integrations/vectara-and-confluent.md
  www/docs/release-notes.mdx
  www/sidebars.js
Labels: New Features

#421 docs(update): Update content and screenshots for the File Upload UI, the Documents UI, and the Query UI
  www/docs/console-ui/configure_queries.md
  www/docs/console-ui/corpora/upload_data_to_corpus.md
  www/sidebars.js
  www/static/img/configure_filters.png
  www/static/img/query_history_tab.png
  www/static/img/query_tab.png
  www/static/img/upload_data_to_corpus_console.png
Labels: Documentation and Feature Enhancements

#423 api(new): Add the Delete LLM API, Get LLM API, and Create Encoder API and Chunking Strategy to the API Reference
  www/docs/rest-api/create-corpus-document.api.mdx
  www/docs/rest-api/create-corpus.api.mdx
  www/docs/rest-api/create-encoder.api.mdx
  www/docs/rest-api/create-user.api.mdx
  www/docs/rest-api/delete-llm.api.mdx
  www/docs/rest-api/get-chat-turn.api.mdx
  www/docs/rest-api/get-chat.api.mdx
  www/docs/rest-api/get-corpus.api.mdx
  www/docs/rest-api/get-job.api.mdx
  www/docs/rest-api/get-llm.api.mdx
  www/docs/rest-api/get-query-histories.api.mdx
  www/docs/rest-api/get-query-history.api.mdx
  www/docs/rest-api/get-user.api.mdx
  www/docs/rest-api/list-chat-turns.api.mdx
  www/docs/rest-api/list-chats.api.mdx
  www/docs/rest-api/list-corpora.api.mdx
  www/docs/rest-api/list-encoders.api.mdx
  www/docs/rest-api/list-jobs.api.mdx
  www/docs/rest-api/list-users.api.mdx
  www/docs/rest-api/reset-user-password.api.mdx
  www/docs/rest-api/sidebar.js
  www/docs/rest-api/update-chat-turn.api.mdx
  www/docs/rest-api/update-corpus.api.mdx
  www/docs/rest-api/update-user.api.mdx
  www/docs/rest-api/upload-file.api.mdx
  www/static/vectara-oas-v2.yaml
Labels: API Changes

#420 feat(new): Add documentation for the tech preview of the expanded LLM Management APIs
  www/docs/api-reference/llms-apis/create-llm.md
  www/docs/api-reference/llms-apis/delete-llm.md
  www/docs/api-reference/llms-apis/get-llm.md
  www/docs/release-notes.mdx
  www/sidebars.js
Labels: New Features

#425 feat(new): Add documentation for the tech preview of the Expanded Encoder Management
  www/docs/api-reference/encoder-apis/create-encoder.md
  www/docs/release-notes.mdx
  www/sidebars.js
Labels: New Features

#427 doc(fix): Clarify that filterable metadata fields are not encrypted
  www/docs/learn/data-privacy/data_encryption.md
Labels: Documentation Fixes

#431 api(update): Update Encoder examples
  www/docs/rest-api/create-corpus.api.mdx
  www/docs/rest-api/create-encoder.api.mdx
  www/docs/rest-api/create-user.api.mdx
  www/docs/rest-api/get-chat-turn.api.mdx
  www/docs/rest-api/get-chat.api.mdx
  www/docs/rest-api/get-corpus.api.mdx
  www/docs/rest-api/get-job.api.mdx
  www/docs/rest-api/get-query-histories.api.mdx
  www/docs/rest-api/get-query-history.api.mdx
  www/docs/rest-api/get-user.api.mdx
  www/docs/rest-api/list-chat-turns.api.mdx
  www/docs/rest-api/list-chats.api.mdx
  www/docs/rest-api/list-corpora.api.mdx
  www/docs/rest-api/list-encoders.api.mdx
  www/docs/rest-api/list-jobs.api.mdx
  www/docs/rest-api/list-users.api.mdx
  www/docs/rest-api/update-chat-turn.api.mdx
  www/docs/rest-api/update-corpus.api.mdx
  www/docs/rest-api/update-user.api.mdx
  www/static/vectara-oas-v2.yaml
Labels: Example Updates

#433 docs(fix): Update Encoder parameters
  www/docs/api-reference/encoder-apis/create-encoder.md
Labels: Documentation Fixes
