Repository vectara/vectara-docs, pull requests merged in 2025-09, with the labels that each got.

#491 feat(new): Introduce the tech preview of the Vectara Agentic Platform
  www/docs/agents/agent-platform-overview.md
  www/docs/agents/agents.md
  www/docs/agents/instructions.md
  www/docs/agents/model-context-protocol.md
  www/docs/agents/sessions.md
  www/docs/agents/tool-servers.md
  www/docs/agents/tools.md
  www/docs/api-reference/agent-apis/agent-apis-overview.md
  www/docs/api-reference/agent-apis/create-agent.md
  www/docs/api-reference/agent-apis/delete-agent.md
  www/docs/api-reference/agent-apis/event/create-agent-event.md
  www/docs/api-reference/agent-apis/event/get-agent-event.md
  www/docs/api-reference/agent-apis/event/list-agent-events.md
  www/docs/api-reference/agent-apis/get-agent.md
  www/docs/api-reference/agent-apis/instruction/create-instruction.md
  www/docs/api-reference/agent-apis/instruction/delete-instruction-version.md
  www/docs/api-reference/agent-apis/instruction/delete-instruction.md
  www/docs/api-reference/agent-apis/instruction/get-instruction.md
  www/docs/api-reference/agent-apis/instruction/list-instructions.md
  www/docs/api-reference/agent-apis/instruction/test-instruction.md
  www/docs/api-reference/agent-apis/instruction/update-instruction.md
  www/docs/api-reference/agent-apis/list-agents.md
  www/docs/api-reference/agent-apis/session/create-agent-session.md
  www/docs/api-reference/agent-apis/session/delete-agent-session.md
  www/docs/api-reference/agent-apis/session/get-agent-session.md
  www/docs/api-reference/agent-apis/session/list-agent-sessions.md
  www/docs/api-reference/agent-apis/session/update-agent-session.md
  www/docs/api-reference/agent-apis/tool-server/create-tool-server.md
  www/docs/api-reference/agent-apis/tool-server/delete-tool-server.md
  www/docs/api-reference/agent-apis/tool-server/get-tool-server.md
  www/docs/api-reference/agent-apis/tool-server/list-tool-servers.md
  www/docs/api-reference/agent-apis/tool-server/sync-tool-server.md
  www/docs/api-reference/agent-apis/tool-server/update-tool-server.md
  www/docs/api-reference/agent-apis/tool/delete-tool.md
  www/docs/api-reference/agent-apis/tool/get-tool.md
  www/docs/api-reference/agent-apis/tool/list-tools.md
  www/docs/api-reference/agent-apis/tool/update-tool.md
  www/docs/api-reference/agent-apis/update-agent.md
  www/docs/api-reference/api-concepts/resource-addressing.md
  www/docs/api-reference/rest.md
  www/docs/console-ui/agents/create-an-agent.md
  www/docs/console-ui/agents/example-agents.md
  www/docs/console-ui/manage-agents.md
  www/docs/release-notes.mdx
  www/docs/welcome.mdx
  www/sidebars.ts
  www/src/css/custom.css
  www/static/img/agents/advanced_tab.png
  www/static/img/agents/agents_page.png
  www/static/img/agents/general_tab.png
  www/static/img/agents/instructions_tab.png
  www/static/img/agents/list_agents.png
  www/static/img/agents/model_tab.png
  www/static/img/agents/tools_override.png
  www/static/img/agents/tools_tab.png
Labels: New Features

#495 docs(api): Enhance API Reference with additional improved examples
  www/docs/rest-api/compute-corpus-size.api.mdx
  www/docs/rest-api/correct-hallucinations.api.mdx
  www/docs/rest-api/create-chat-turn.api.mdx
  www/docs/rest-api/create-chat.api.mdx
  www/docs/rest-api/create-corpus-document.api.mdx
  www/docs/rest-api/create-corpus.api.mdx
  www/docs/rest-api/create-encoder.api.mdx
  www/docs/rest-api/create-llm.api.mdx
  www/docs/rest-api/evaluate-factual-consistency.api.mdx
  www/docs/rest-api/get-corpus-document.api.mdx
  www/docs/rest-api/get-corpus.api.mdx
  www/docs/rest-api/get-job.api.mdx
  www/docs/rest-api/get-llm.api.mdx
  www/docs/rest-api/get-query-histories.api.mdx
  www/docs/rest-api/get-query-history.api.mdx
  www/docs/rest-api/list-corpora.api.mdx
  www/docs/rest-api/list-corpus-documents.api.mdx
  www/docs/rest-api/list-generation-presets.api.mdx
  www/docs/rest-api/list-hallucination-correctors.api.mdx
  www/docs/rest-api/list-jobs.api.mdx
  www/docs/rest-api/list-ll-ms.api.mdx
  www/docs/rest-api/query-corpus.api.mdx
  www/docs/rest-api/query.api.mdx
  www/docs/rest-api/replace-corpus-document-metadata.api.mdx
  www/docs/rest-api/replace-filter-attributes.api.mdx
  www/docs/rest-api/search-corpus.api.mdx
  www/docs/rest-api/summarize-corpus-document.api.mdx
  www/docs/rest-api/update-corpus-document.api.mdx
  www/docs/rest-api/update-corpus.api.mdx
  www/docs/rest-api/upload-file.api.mdx
  www/static/vectara-oas-v2.yaml
Labels: API Changes

#498 docs(new): Introduce new section about Private Deployment options such as on premise
  www/docs/api-jumpstart.md
  www/docs/data-management.mdx
  www/docs/deployments.mdx
  www/docs/deployments/deployment-options.md
  www/docs/deployments/guides.mdx
  www/docs/deployments/guides/vectara-okta-oidc.md
  www/docs/deployments/onprem-evaluation-process.md
  www/docs/deployments/private-deployment-overview.md
  www/docs/deployments/use-cases.md
  www/docs/welcome.mdx
  www/docusaurus.config.ts
  www/sidebars.ts
Labels: Documentation and Feature Enhancements

#504 Fix MCP broken link in the agents page
  www/docs/agents/agent-platform-overview.md
Labels: Documentation Fixes
